development:
  adapter: postgresql
  encoding: unicode
  database: frameit
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: frameit_test
  pool: 5
  username: gschool
  password: