development:
  adapter: postgresql
  encoding: unicode
  database: yourock
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: testyourock
  pool: 5
  username: gschool
  password: